### PR TITLE
use released grunt plugin for Galen

### PR DESCRIPTION
**Pull request by hypery2k**

### CODE REVIEW

**Comment by michaseel** [comment]
Ok, you forked grunt-galen to grunt-galenframework. I was thinking about that too, because mjurczyk is very slow with PR´s.

**Comment by michaseel** [comment]
@hypery2k could you give me write access to grunt-galenframework repo and npm?

**Comment by hypery2k** [comment]
i currently refactoring the plugin. Once I've finished and added reliable test I'll gave you write access

**Comment by hypery2k** [comment]
I gave you write access to the GitHub repo. For now I don't know how to add you to npm

**Comment by michaseel** [comment]
Thanks! For npm go to https://www.npmjs.com/package/grunt-galenframework and login.
Then you see a "+" Button under "Collaborators". 
Or look at the owner man: https://docs.npmjs.com/cli/owner
My npm username is "michaseel"

**Comment by hypery2k** [comment]
thanks, I've added you

**Pull request merged**
